
x1 = data1_1;
x2 = data2_1;
x3 = data3_1;
x = [x1;x2;x3];
x=x(:);
g1 = [ones(size(x1)); 2*ones(size(x2)); 3*ones(size(x3))]; g1 = g1(:);
g2 = repmat(1:6,120,1); g2 = g2(:);
f = figure,
% boxplot(x, {g1,g2},'notch','on', 'colorgroup',g1, 'factorgap',5, 'factorseparator',1)
boxplot(x, {g1,g2},'notch','on', 'colorgroup',g1, 'factorgap',5)
xlabel('Incident Probability [%]');
% xlabel('Strategies');
ylabel('Scanning Distance [km]')
grid on
set(gca,'YLim',[4,6],'gridLineStyle', '-.');
% set(bh,'linewidth',1.2);
set(gca,'xtick',[7,14])
set(gca,'XTickLabel',{' '})

% hLegend = legend(findall(gca,'Tag','Box'), {'GMopt','GRelax','GAdapt'});
% 
% Create textbox
% annotation(f,'textbox',...
%     [0.16 0.075 0.035 0.075],...
%     'String',{'0.8'},...
%     'FitBoxToText','off',...
%     'EdgeColor','none');
% 
% % Create textbox
% annotation(f,'textbox',...
%     [0.29 0.075 0.035 0.075],...
%     'String','1.7',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');
% 
% % Create textbox
% annotation(f,'textbox',...
%     [0.42 0.075 0.035 0.075],...
%     'String','2.5',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');
%  
% % Create textbox
% annotation(f,'textbox',...
%     [0.55 0.075 0.035 0.075],...
%     'String','3.3',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');
% 
% % Create textbox
% annotation(f,'textbox',...
%     [0.68 0.075 0.035 0.075],...
%     'String','4.2',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');
% 
% % Create textbox
% annotation(f,'textbox',...
%     [0.81 0.075 0.035 0.075],...
%     'String','5.0',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');


annotation(f,'textbox',...
    [0.22 0.075 0.035 0.075],...
    'String','GMopt',...
    'FitBoxToText','off',...
    'Fontname', 'Times New Roman',...
    'EdgeColor','none');

annotation(f,'textbox',...
    [0.47 0.075 0.035 0.075],...
    'String','GRelax',...
    'FitBoxToText','off',...
    'Fontname', 'Times New Roman',...
    'EdgeColor','none');

annotation(f,'textbox',...
    [0.73 0.075 0.035 0.075],...
    'String','GAdapt',...
    'FitBoxToText','off',...
    'Fontname', 'Times New Roman',...
    'EdgeColor','none');
set(gca,'fontname','Times');